### ISSUE TITLE
Block :  not saving configure tab fields

### ISSUE THREAD

**Issue by trk** [luyadev/luya-module-cms#101]
In `Block` edit mode: if configure tab not opened (never opened), not saving `configure tab` fields.

i have `html_element` config variable on `configure tab`. As you see on `screenshot`, when i visit `configure tab`, i can get values for configs.

![2018-06-20 19 48 16](https://user-images.githubusercontent.com/455983/41672620-076b3590-74c3-11e8-9a95-919bbc745db6.gif)

**Comment by nadar** [comment]
@trk could please provide the block config() section?

**Comment by nadar** [comment]
I am going to close this issue because:

- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our slack team: slack.luya.io. We try to keep our issue tracker as clean as possible in order to focus on active issues.
