### ISSUE TITLE
remove public_html form url address (cms page)

### ISSUE THREAD

**Issue by msoa** [luyadev/luya-module-cms#135]
There is a page named `about`, address is `http://host.com/public_html/about`
How can remove `public_html` from url?

`http://host.com/about` => page not found with 200 status

Via this rule:
`'about' => '/cms/default/index/path/about',`
`http://host.com/web/about` => page not found 404
`http://host.com/about` => page not found with 200 status

.htaccess on `public_html` host provider
```
Options -Indexes
IndexIgnore */*

Options FollowSymlinks
RewriteEngine on
RewriteRule ^(.+)?$ public_html/$1
```

**Comment by nadar** [comment]
Hi @msoa In order to remove the public_html from your address you should configure the webserver you are running the website. You have to make `public_html` the **document root** the webserver is listening to:

Apache: https://stackoverflow.com/questions/5891802/how-do-i-change-the-root-directory-of-an-apache-server
nginx: https://stackoverflow.com/questions/10674867/nginx-default-public-www-location
on plesk: https://www.a2hosting.com/kb/a2-hosting-products/windows-hosting/changing-the-document-root-directory-in-plesk
cpanel: https://www.servint.net/university/article/the-tech-bench-changing-a-document-root-in-cpanel/
