### ISSUE TITLE
LangSwitcher and Module page 

### ISSUE THREAD

**Issue by Antikon** [luyadev/luya-module-cms#260]
### What steps will reproduce the problem?
We have a page **Statistics** which is Module. It refers to `StatsController` and `show-stats` action.

Let's navigate to that page. We have URL `http://site/ru/statistics`

Now switch to EN language.

### What is the expected result?
We should see **Statistics** in English (which is Module page also) with URL `http://site/en/statistics`

### What do you get instead?
We have **Statistics** in English but the URL is `http://site/en/statistics/stats/show-stats`

This wrong URL comes from LangSwitcher widget.

**Comment by nadar** [comment]
have you defined an url rule in the module?

**Comment by Antikon** [comment]
No.

**Comment by nadar** [comment]
Could you try that? So luya knows the rule and can prefix the current page correctly.

**Comment by nadar** [comment]
> If you are using the module in a CMS context your patterns must be prefix with the module name, otherwise the CMS can not auto replace the new pattern with the CMS context information. For example redirecting from controller foo action index to controller bar action index inside a module both url rules must be prefix. For foo ['MODULE/name-for-foo-index' => 'MODULE/foo/index'] for bar ['MODULE/name-for-bar-index' => 'MODULE/bar/index'] so they must have the full qualified route with the name of the module used in the config to register the module. Also the patterns must prefix the module name.

https://luya.io/guide/app-module-urlrules

maybe this helps

**Comment by nadar** [comment]
I am going to close this issue because:

- Its a question (Please post questions at [forum.luya.io](https://forum.luya.io))
- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our forum: [forum.luya.io](https://forum.luya.io). We try to keep our issue tracker as clean as possible in order to focus on active issues.
