### ISSUE TITLE
Canonical

### ISSUE THREAD

**Issue by boehsermoe** [luyadev/luya-module-cms#271]
In https://github.com/luyadev/luya-module-cms/blob/master/src/frontend/base/Controller.php#L191 the canonical url always the same like the requested url. 
For google the url http://localhost/ and http://localhost/?foo=bar will be two different pages but with same content -> also duplicate content.

The canonical url should be the generated route of the current cms page and not the requested url.

**Comment by nadar** [comment]
To "generate" the canoncal url seems not to be easy. Then maybe we should remove the property.

**Comment by boehsermoe** [comment]
Yes I agree. I don't know any reason for it on a cms page

**Comment by JohnnyMcWeed** [comment]
I think this should be reopened, as the issue is not solved and puts problems in terms of duplicate content when using custom modules.
E. g. take the luya-module-news.
+ It can be added as a module to the cms nav.
+ It can be added as a module to a page
+ It is accessible by it's module name

This brings up three different urls for the same page -> duplicate content....

**Comment by nadar** [comment]
Indeed, but the solution we have implemented did not fix the problem either.

Personally i think this is not a problem. If people include the same content under different URLs something with the concept is wrong anyhow.

**Comment by JohnnyMcWeed** [comment]
I completely agree with you :)
Maybe open as reminder for future feature, as we can't know every business reason for such a thing? ;)

**Comment by boehsermoe** [comment]
We cannot define a generic solution for all the scenarios. So I the best is if the canonical url is configurable in the page infos, where you can link to another page. But this is a own ticket.
