### ISSUE TITLE
How to convert application/octet-stream to pdf?

### ISSUE THREAD

**Issue by S10hivam** [luyadev/luya-module-cms#287]
File Type: data
MIME Type: application/octet-stream;
Suggested file extension(s): bin lha lzh exe class so dll img iso

Please Suggest How to Convert above file to pdf?

**Comment by nadar** [comment]
Hi. Sorry i don't understand how this is related to LUYA cms?

**Comment by nadar** [comment]
I am going to close this issue because:

- Its a question (Please post questions at [forum.luya.io](https://forum.luya.io))
- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our forum: [forum.luya.io](https://forum.luya.io). We try to keep our issue tracker as clean as possible in order to focus on active issues.
