### ISSUE TITLE
Display problems with multiple radio button fields in CMS block

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya-module-cms#308]
### What steps will reproduce the problem?

Create a block with multiple self::TYPE_RADIO var fields.

### What is the expected result?

The selected radio buttons of all fields should be displayed as selected.

### What do you get instead? (A Screenshot can help us a lot!)

Only the selected radio button of the last field is displayed as selected:

![image](https://user-images.githubusercontent.com/3786245/97164743-df089100-1782-11eb-99ed-1f1883eeeb53.png)

The values are still stored correctly, it only seems to be a display problem.

LUYA Version  1.7.1

**Comment by nadar** [comment]
I will do some research.

@TheMaaarc i am not sure, but i guess we know this problem already when multiple checkboxes are used on the same page?

**Comment by nadar** [comment]
@TheMaaarc we already have discuss this problem internally, because it appears also in the export window:

<img width="488" alt="Bildschirmfoto 2020-10-26 um 18 53 11" src="https://user-images.githubusercontent.com/3417221/97209393-94a40600-17bc-11eb-9898-f4446d361b87.png">

(therefore we have removed the "kopfzeile" function because of the checkboxes issue)

The checked state is correctly set:

<img width="999" alt="Bildschirmfoto 2020-10-26 um 18 56 52" src="https://user-images.githubusercontent.com/3417221/97209926-33306700-17bd-11eb-9aec-d80dcb3d831c.png">

So its maybe a css problem?

**Comment by hbugdoll** [comment]
zaa radio buttons have unique `name` attribute (`name="{{id}}_{{key}}"`) like `id` attribute,
but they need the same `name` attribute (`name="{{id}}"`).

I made a PR: https://github.com/luyadev/luya-module-admin/pull/662/
